In [1]:
import numpy as np

# Array creation Conversion from other python structure

** to create an array **

In [2]:
myarr = np.array([3,4,6,2])

In [3]:
myarr

array([3, 4, 6, 2])

** create numpy array with datatype **

In [4]:
myarr1 = np.array([34,2,56,2], np.int64)

In [5]:
myarr1

array([34,  2, 56,  2], dtype=int64)

** to access element from 1D **

In [6]:
myarr1[2]

56

** create 2D numpy array **

In [7]:
myarr2 = np.array([[34,2,6,2]], np.int32)

** access element from 2D &&

In [8]:
myarr2[0][2]

6

# shape method

In [9]:
myarr2.shape

(1, 4)

# dtype method

In [10]:
myarr2.dtype

dtype('int32')

** change particular element of an array **

In [11]:
myarr2[0][2] = 26

In [12]:
myarr2

array([[34,  2, 26,  2]])

** to check size of an array **

In [13]:
myarr2.size

4

** when we insert dict as **

In [14]:
np.array({32,2,56})

array({32, 2, 56}, dtype=object)

# *array creation using common numpy methods

# zeros() mthod create array with zeros 

In [15]:
zeros = np.zeros((2,3))

In [16]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 3)

# arange()method give array of n-1 i.e (6-1) 

In [19]:
rng = np.arange(6)

In [20]:
rng

array([0, 1, 2, 3, 4, 5])

# linspace()method create array with equaly difference from 1to5 with 7 array elements

In [21]:
lspace = np.linspace(1,5,7)

In [22]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

# empty()method create empty array with random values 

In [23]:
emp = np.empty((2,2))

In [24]:
emp

array([[2.44029516e-312, 2.05833592e-312],
       [2.14321575e-312, 8.90104239e-307]])

# empty_like()method create array from previous creted array with same size 

In [25]:
emp_like = np.empty_like(rng)

In [26]:
emp_like

array([98,  0,  0,  0,  0,  0])

# identity()method create array of identity matrix 

In [27]:
ide = np.identity(5)

In [28]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
ide.shape

(5, 5)

# reshape()method 

In [30]:
arr = np.arange(22)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [32]:
arr.reshape(2,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [34]:
arr = arr.reshape(2,11)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [36]:
arr.shape

(2, 11)

# to make 1D array use ravel()method 

In [37]:
arr = arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [39]:
arr.shape

(22,)

# numpy axis 

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

# numpy common attributes

** transpose attribute **

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

** flat used to iterate array **

In [46]:
ar.flat

In [47]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


** ndim used to give dimensations of array **

In [48]:
ar.ndim

2

** size attribute **

In [49]:
ar.size

9

** nbytes attribute return no of bytes consumed by array **

In [50]:
ar.nbytes

36

# *numpy methods

In [51]:
one = np.array((1,2,3,45,6))

# arg methods

** argmax() return index of maximum element in array **

In [52]:
one.argmax()

3

** argmin()return minimum element's index **

In [53]:
one.argmin()

0

** argsort() return index according to sorting array elements **

In [54]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int32)

# perform all args methods on 2D as- 

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [57]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [58]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [59]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int32)

In [60]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [61]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

# sqrt() method 

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

# sum() method 

In [65]:
ar.sum()

29

# min() & max() methods 

In [66]:
ar.max()

7

In [67]:
ar.min()

0

** to search element in an array **

In [68]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [69]:
ar1 = ([[2, 2, 3],
       [4, 3, 2],
       [2, 1, 0]])

** to check type of array **

In [70]:
type(np.where(ar>5))

tuple

# count nonzero elements 

In [71]:
np.count_nonzero(ar)

8

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

# size method

In [73]:
ar.size

9

# sort method

In [74]:
np.sort(ar)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

# tolist method

In [75]:
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

# append method

In [76]:
np.append(ar,33)

array([ 1,  2,  3,  4,  5,  6,  7,  1,  0, 33])

# insert method

In [77]:
np.insert(ar,2,44)

array([ 1,  2, 44,  3,  4,  5,  6,  7,  1,  0])

# random method

In [78]:
np.random.rand(2,3)

array([[0.70413106, 0.39418752, 0.00985646],
       [0.03091383, 0.32474551, 0.50419233]])

# *common operators

** + operator **

In [79]:
ar + ar1

array([[3, 4, 6],
       [8, 8, 8],
       [9, 2, 0]])

** multiply operator **

In [80]:
ar * ar1

array([[ 2,  4,  9],
       [16, 15, 12],
       [14,  1,  0]])

** -operator **

In [81]:
ar - ar1

array([[-1,  0,  0],
       [ 0,  2,  4],
       [ 5,  0,  0]])

# *slicing

# slicing on 1D

In [82]:
a = np.array([2,3,1,2,4])

In [83]:
a[0:3]

array([2, 3, 1])

In [84]:
a[::]

array([2, 3, 1, 2, 4])

# slicing on 2D

In [85]:
a1 = np.array([[2, 3], [1, 2], [4,5]])

In [86]:
a1

array([[2, 3],
       [1, 2],
       [4, 5]])

In [87]:
a1[0:,1:]

array([[3],
       [2],
       [5]])

# slicing on 3D

In [88]:
a2 = np.array([[[1,2,3],[2,3,4],[4,5,6]]])

In [89]:
a2

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [90]:
a2[:,1:,::1]

array([[[2, 3, 4],
        [4, 5, 6]]])